// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dngvnznbpgljeezcdxep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRuZ3Zuem5icGdsamVlemNkeGVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNDY1MDAsImV4cCI6MjA3MDYyMjUwMH0.WWkxYEq_2njRiL6Ztg_jAtag3KOHPcyO_c9DE5CCcjQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});